export enum OrderStatus {
  PENDING = 'PENDING',
  PAYMENT_PROCESSING = 'PAYMENT_PROCESSING',
  PAYMENT_COMPLETED = 'PAYMENT_COMPLETED',
  STOCK_DEDUCTION = 'STOCK_DEDUCTION',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
