services:
  mysql-master:
    build:
      context: ./mysql/master
      args:
        SERVER_ID: 1
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: testdb
    ports:
      - "3307:3306"
    volumes:
      - master-data:/var/lib/mysql
    networks:
      utils-network:
        - ipv4_address: 172.20.0.3
  mysql-replica1:
    build:
      context: ./mysql/replica
      args:
        SERVER_REPLICA_ID: 2
    container_name: mysql-replica1
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: testdb
    ports:
      - "3308:3306"
    volumes:
      - replica1-data:/var/lib/mysql
    depends_on:
      - mysql-master
    networks:
      utils-network:
        - ipv4_address: 172.20.0.4
  mysql-replica2:
    build:
      context: ./mysql/replica
      args:
        SERVER_REPLICA_ID: 3
    container_name: mysql-replica2
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: testdb
    ports:
      - "3309:3306"
    volumes:
      - replica2-data:/var/lib/mysql
    depends_on:
      - mysql-master
    networks:
      utils-network:
        - ipv4_address: 172.20.0.5

volumes:
  master-data:
  replica1-data:
  replica2-data:

networks:
  utils-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
